default_context:
    domain_name: cov.ing/covey/
    github_actions_env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ vars.CLOUDFLARE_ZONE_ID }}
        GITHUB_TOKEN: ${{ github.token }}
        PATH: .venv/bin:/home/runner/.local/bin:/home/runner/.local/share/mise/shims:/usr/bin:/bin
        TF_CLI_ARGS_apply: -auto-approve -input=false
    languages: Node,Python,Terraform
    node_dev_dependencies:
        '@prettier/plugin-xml': ^3.4.2
    python_dependencies:
        - helicopyter
        - sitemapy
        - zensical
    python_optional_dependencies:
        test:
            - html5lib
    python_version: '3.13'
